version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  pre_build:
    commands:
      - echo "Preparing to build"
  build:
    commands:
      - ./hello.sh
  post_build:
    commands:
      - echo "Build complete"
